#!/bin/sh
# Set version and publish package

VERSION=$1
if test -z "$VERSION"; then
    echo VERSION must be set
    exit 1
fi

rpl 'version = .*' "version = $VERSION" Cargo.toml
git ci -m "Bump Cargo version to $VERSION" Cargo.toml && git push
npm version $VERSION
npm publish
cargo publish
